import * as THREE from 'three';
import {
  mulberry32, fbm, ridged, warp, blur3, remap, normalize01, clamp01, smoothstep, lerp,
  stampDome, stampBlob, stampSegment, stampCrack, stampStreak,
  normalFromHeight, aoFromHeight,
} from './fields.js';

/**
 * texgen.js — the procedural PBR texture library. Zero external assets.
 *
 * Each entry produces a tiling set:
 *    map        sRGB albedo
 *    normalMap  tangent-space, SOBEL-DERIVED from the same height field that
 *               drives the AO — so cracks, mortar joints and panel seams line
 *               up across all three maps instead of floating independently.
 *    ormMap     R = ambient occlusion (cavity), G = roughness, B = metalness
 *               (the glTF packing; three reads .r/.g/.b for ao/rough/metal, so
 *               one texture and one sampler serves all three)
 *
 * Authoring rule from the art bible: surface detail must exist at THREE
 * frequencies or it reads as plastic —
 *    macro  (0.5-3 m)  large blotches, staining, damage zones, paint loss
 *    meso   (2-20 cm)  cracks, panel seams, mortar, plank edges, dents
 *    micro  (< 1 cm)   aggregate, grain, weave, pitting
 * Every generator below builds all three explicitly.
 *
 * `tileMetres` is the real-world size of one UV tile. Geometry UVs are
 * generated by world-space planar projection divided by this number, so a
 * texture is physically the same size on every surface in the level and the
 * classic "wrong tiling scale" tell cannot happen.
 */

const HEX = (h) => [((h >> 16) & 255) / 255, ((h >> 8) & 255) / 255, (h & 255) / 255];

// palette (sRGB) — mirrors artdirection.PALETTE, kept local so texture authoring
// can nudge a value without editing the bible.
const C = {
  concrete: HEX(0x8f8b83), concreteDark: HEX(0x605d58), concretePale: HEX(0xb0aa9f),
  sand: HEX(0xbfa984), sandDark: HEX(0x8d7a5c), sandPale: HEX(0xd8c6a4),
  rust: HEX(0x7a4a2c), rustLight: HEX(0xa2683c), rustDark: HEX(0x4a2c1c),
  steel: HEX(0x8a8f94), steelDark: HEX(0x5a5f64), zinc: HEX(0x9aa0a4),
  paintedTan: HEX(0xa8916b), asphalt: HEX(0x3f3d3c), asphaltPatch: HEX(0x2c2b2b),
  wood: HEX(0x9b7a4e), woodDark: HEX(0x6a5031), sandbag: HEX(0xa89573),
  brick: HEX(0x8a5a44), brickDark: HEX(0x6b4231), mortar: HEX(0x9c968a),
  plaster: HEX(0xbfb5a4), moss: HEX(0x5c5b46), grime: HEX(0x3a352d),
};

// ---------------------------------------------------------------------------
// albedo helpers — three parallel Float32 planes, sRGB 0..1
// ---------------------------------------------------------------------------
function rgbPlanes(n, c) {
  const R = new Float32Array(n), G = new Float32Array(n), B = new Float32Array(n);
  R.fill(c[0]); G.fill(c[1]); B.fill(c[2]);
  return [R, G, B];
}
function blendMask(P, c, mask, strength = 1, bias = 0) {
  const [R, G, B] = P;
  for (let i = 0; i < R.length; i++) {
    const t = clamp01((mask[i] + bias) * strength);
    R[i] += (c[0] - R[i]) * t; G[i] += (c[1] - G[i]) * t; B[i] += (c[2] - B[i]) * t;
  }
}
function shadeByField(P, f, lo, hi) {
  const [R, G, B] = P;
  for (let i = 0; i < R.length; i++) {
    const k = lo + (hi - lo) * f[i];
    R[i] *= k; G[i] *= k; B[i] *= k;
  }
}
function jitterHue(P, rnd, amt) {
  const [R, G, B] = P;
  for (let i = 0; i < R.length; i++) {
    R[i] *= 1 + (rnd() - 0.5) * amt; G[i] *= 1 + (rnd() - 0.5) * amt; B[i] *= 1 + (rnd() - 0.5) * amt;
  }
}

function toBytes(P, size) {
  const n = size * size, out = new Uint8Array(n * 4);
  const [R, G, B] = P;
  for (let i = 0; i < n; i++) {
    const j = i * 4;
    out[j] = clamp01(R[i]) * 255; out[j + 1] = clamp01(G[i]) * 255; out[j + 2] = clamp01(B[i]) * 255; out[j + 3] = 255;
  }
  return out;
}
function packORM(ao, rough, metal, size) {
  const n = size * size, out = new Uint8Array(n * 4);
  for (let i = 0; i < n; i++) {
    const j = i * 4;
    out[j] = clamp01(ao[i]) * 255;
    out[j + 1] = clamp01(Math.max(0.08, rough[i])) * 255;   // bible: never below 0.08
    out[j + 2] = clamp01(metal[i]) * 255;
    out[j + 3] = 255;
  }
  return out;
}

function makeTex(bytes, size, srgb, aniso) {
  const t = new THREE.DataTexture(bytes, size, size, THREE.RGBAFormat, THREE.UnsignedByteType);
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.magFilter = THREE.LinearFilter;
  t.minFilter = THREE.LinearMipmapLinearFilter;
  t.generateMipmaps = true;
  t.anisotropy = aniso;
  if (srgb) t.colorSpace = THREE.SRGBColorSpace;
  t.needsUpdate = true;
  return t;
}

// ===========================================================================
// GENERATORS
// Each returns { albedo:[R,G,B], height, rough, metal, alpha?, heightMetres,
//                tileMetres, size, aoStrength? }
// ===========================================================================

// --- cracked concrete ------------------------------------------------------
function genConcrete(size) {
  const n = size * size, rnd = mulberry32(1337);
  const macro = warp(fbm(size, 4, 7, 11), size, fbm(size, 8, 4, 21), fbm(size, 8, 4, 22), size * 0.05);
  const meso = fbm(size, 24, 6, 31);
  const micro = fbm(size, 160, 3, 41);
  const patchy = remap(fbm(size, 6, 5, 51), 0.42, 0.62);

  // ---- height: slab relief + form-board joints + aggregate pitting + cracks
  const h = new Float32Array(n);
  for (let i = 0; i < n; i++) h[i] = macro[i] * 0.45 + meso[i] * 0.32 + micro[i] * 0.1;
  // formwork board lines: shallow horizontal joints every quarter tile
  for (let k = 0; k < 4; k++) {
    const y = (k + 0.5) * size / 4 + (rnd() - 0.5) * 4;
    stampSegment(h, size, -2, y, size + 2, y + (rnd() - 0.5) * 3, 3.5, -0.16);
    stampSegment(h, size, -2, y - 2, size + 2, y - 2, 1.6, 0.05);
  }
  // exposed aggregate + air voids (blow-holes) — the micro read of poured concrete
  for (let i = 0; i < 1500; i++) {
    const x = rnd() * size, y = rnd() * size, r = 1.2 + rnd() * 4.5;
    stampDome(h, size, x, y, r, (rnd() < 0.42 ? -0.28 : 0.14) * (0.5 + rnd()), 0.7);
  }
  // spalled patches where the surface has broken away to aggregate
  const spall = new Float32Array(n);
  for (let i = 0; i < 9; i++) {
    const x = rnd() * size, y = rnd() * size, r = size * (0.02 + rnd() * 0.05);
    stampBlob(spall, size, x, y, r, 1, 1, 0.86);
    stampDome(h, size, x, y, r, -0.2, 1.4);
  }
  // crack network
  for (let i = 0; i < 16; i++) {
    stampCrack(h, size, rnd, {
      length: size * (0.15 + rnd() * 0.5), width: 1.6 + rnd() * 2.6,
      amp: -0.5 - rnd() * 0.4, wander: 0.3, branch: 0.7,
    });
  }
  const height = normalize01(h);

  // ---- albedo
  const P = rgbPlanes(n, C.concrete);
  blendMask(P, C.concreteDark, macro, 1.15, -0.42);
  blendMask(P, C.concretePale, patchy, 0.7);
  blendMask(P, C.grime, remap(macro, 0.62, 0.9), 0.55);      // grime in the low spots
  blendMask(P, C.concreteDark, spall, 0.8);
  shadeByField(P, micro, 0.9, 1.1);
  // rebar rust bleed — two or three stained zones, always near a crack
  for (let i = 0; i < 5; i++) {
    const x = rnd() * size, y = rnd() * size;
    const m = new Float32Array(n);
    stampBlob(m, size, x, y, size * (0.03 + rnd() * 0.06), 1, 1, 0.2);
    for (let s = 0; s < 6; s++) stampStreak(m, size, x + (rnd() - 0.5) * 40, y, 60 + rnd() * 140, 2 + rnd() * 5, 0.9);
    blendMask(P, rnd() < 0.5 ? C.rust : C.rustDark, m, 0.5);
  }
  // dirt streaks running down (gravity always wins on a vertical surface)
  const streaks = new Float32Array(n);
  for (let i = 0; i < 34; i++) stampStreak(streaks, size, rnd() * size, rnd() * size, 60 + rnd() * 260, 3 + rnd() * 11, 0.75);
  blendMask(P, C.grime, streaks, 0.34);
  // crack lines darken the albedo too
  const dark = remap(height, 0.0, 0.28);
  for (let i = 0; i < n; i++) { const k = 0.45 + 0.55 * dark[i]; P[0][i] *= k; P[1][i] *= k; P[2][i] *= k; }
  jitterHue(P, rnd, 0.05);

  // ---- roughness / metalness
  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    let r = 0.74 + micro[i] * 0.2 + (macro[i] - 0.5) * 0.14;
    r -= patchy[i] * 0.12;              // polished/burnished patches
    r += spall[i] * 0.12;               // exposed aggregate is rougher
    r -= streaks[i] * 0.14;             // water runs leave a smoother sheen
    rough[i] = clamp01(r);
  }
  return { albedo: P, height, rough, metal, heightMetres: 0.016, tileMetres: 2.6, size };
}

// --- sand / gravel ground --------------------------------------------------
function genSand(size) {
  const n = size * size, rnd = mulberry32(777);
  const macro = fbm(size, 3, 7, 101);
  const drift = warp(fbm(size, 10, 5, 111), size, fbm(size, 6, 4, 112), fbm(size, 6, 4, 113), size * 0.03);
  const micro = fbm(size, 200, 2, 121);
  const gravelMask = remap(fbm(size, 7, 5, 131), 0.5, 0.72);

  const h = new Float32Array(n);
  // wind ripples: a warped sine so they meander instead of marching in rank
  for (let y = 0, i = 0; y < size; y++) {
    for (let x = 0; x < size; x++, i++) {
      const ph = (x * 0.055 + drift[i] * 9 + macro[i] * 22);
      h[i] = macro[i] * 0.5 + drift[i] * 0.22 + Math.sin(ph) * 0.055 * (0.35 + 0.65 * (1 - gravelMask[i])) + micro[i] * 0.05;
    }
  }
  // pebbles: dense in the gravel zones, sparse elsewhere
  for (let i = 0; i < 5200; i++) {
    const x = rnd() * size, y = rnd() * size;
    const g = gravelMask[(y | 0) * size + (x | 0)];
    if (rnd() > 0.15 + g * 0.95) continue;
    const r = 1.1 + rnd() * (2.2 + g * 5.5);
    stampDome(h, size, x, y, r, 0.16 + rnd() * 0.3, 0.55);
  }
  // scuffs / boot drag
  for (let i = 0; i < 26; i++) {
    const a = rnd() * Math.PI * 2, x = rnd() * size, y = rnd() * size, L = 20 + rnd() * 90;
    stampSegment(h, size, x, y, x + Math.cos(a) * L, y + Math.sin(a) * L, 5 + rnd() * 12, -0.1);
  }
  const height = normalize01(h);

  const P = rgbPlanes(n, C.sand);
  blendMask(P, C.sandDark, macro, 1.2, -0.4);
  blendMask(P, C.sandPale, remap(drift, 0.5, 0.85), 0.75);
  blendMask(P, C.concreteDark, gravelMask, 0.62);
  blendMask(P, C.grime, remap(macro, 0.7, 1.0), 0.3);
  shadeByField(P, height, 0.82, 1.14);
  shadeByField(P, micro, 0.94, 1.06);
  jitterHue(P, rnd, 0.06);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) rough[i] = clamp01(0.93 + micro[i] * 0.08 - gravelMask[i] * 0.16 - macro[i] * 0.05);
  return { albedo: P, height, rough, metal, heightMetres: 0.028, tileMetres: 3.4, size };
}

// --- asphalt with patches --------------------------------------------------
function genAsphalt(size) {
  const n = size * size, rnd = mulberry32(4242);
  const macro = fbm(size, 5, 6, 201);
  const micro = fbm(size, 180, 3, 211);
  const patch = remap(warp(fbm(size, 5, 5, 221), size, fbm(size, 7, 4, 222), fbm(size, 7, 4, 223), size * 0.04), 0.46, 0.56);
  const dust = remap(fbm(size, 9, 5, 231), 0.44, 0.78);

  const h = new Float32Array(n);
  for (let i = 0; i < n; i++) h[i] = macro[i] * 0.22 + micro[i] * 0.16;
  for (let i = 0; i < 6500; i++) {   // bitumen aggregate
    const x = rnd() * size, y = rnd() * size;
    stampDome(h, size, x, y, 1 + rnd() * 3.2, 0.1 + rnd() * 0.22, 0.6);
  }
  // patch edges sit slightly proud with a lipped seam
  for (let i = 0; i < n; i++) h[i] += patch[i] * 0.16;
  for (let i = 0; i < 22; i++) {
    stampCrack(h, size, rnd, { length: size * (0.2 + rnd() * 0.6), width: 1.5 + rnd() * 3, amp: -0.55, wander: 0.34, branch: 0.9 });
  }
  // potholes
  for (let i = 0; i < 4; i++) {
    const x = rnd() * size, y = rnd() * size, r = 8 + rnd() * 22;
    stampDome(h, size, x, y, r, -0.55, 1.6);
  }
  const height = normalize01(h);

  const P = rgbPlanes(n, C.asphalt);
  blendMask(P, C.asphaltPatch, patch, 0.9);
  blendMask(P, C.steelDark, remap(micro, 0.55, 0.95), 0.28);   // aggregate stones
  blendMask(P, C.sand, dust, 0.5);                              // wind-blown sand
  shadeByField(P, macro, 0.82, 1.15);
  // tyre polish: two dark burnished bands
  const tyre = new Float32Array(n);
  for (let k = 0; k < 2; k++) {
    const x = size * (0.28 + k * 0.42);
    for (let s = 0; s < 12; s++) stampStreak(tyre, size, x + (rnd() - 0.5) * 26, rnd() * size, size, 10 + rnd() * 16, 0.7);
  }
  blendMask(P, C.grime, tyre, 0.45);
  jitterHue(P, rnd, 0.05);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) rough[i] = clamp01(0.78 + micro[i] * 0.16 - patch[i] * 0.16 - tyre[i] * 0.22 + dust[i] * 0.12);
  return { albedo: P, height, rough, metal, heightMetres: 0.012, tileMetres: 4.0, size };
}

// --- corrugated metal sheet ------------------------------------------------
function genCorrugated(size) {
  const n = size * size, rnd = mulberry32(909);
  const RIDGES = 13;                       // ~154 mm pitch over a 2 m tile
  const macro = fbm(size, 6, 6, 301);
  const micro = fbm(size, 220, 2, 311);
  // Rust reads as weathering only at a fine scale. A low base frequency plus a
  // strong warp produces huge amoeba-shaped patches that look like a world map.
  const rustMask = remap(warp(fbm(size, 13, 6, 321), size, fbm(size, 9, 4, 322), fbm(size, 9, 4, 323), size * 0.018), 0.52, 0.80);
  const spangle = fbm(size, 40, 3, 331);   // galvanised zinc crystal mottling

  const h = new Float32Array(n);
  for (let y = 0, i = 0; y < size; y++) {
    for (let x = 0; x < size; x++, i++) {
      const u = (x / size) * RIDGES;
      const f = u - Math.floor(u);
      // trapezoidal profile: flat crest, sloped web, flat valley
      let p;
      if (f < 0.18) p = 1; else if (f < 0.42) p = 1 - (f - 0.18) / 0.24;
      else if (f < 0.6) p = 0; else if (f < 0.84) p = (f - 0.6) / 0.24; else p = 1;
      h[i] = p * 0.78 + micro[i] * 0.05 + macro[i] * 0.06;
    }
  }
  // dents and impact dings
  for (let i = 0; i < 40; i++) stampDome(h, size, rnd() * size, rnd() * size, 4 + rnd() * 26, -0.16 - rnd() * 0.2, 1.1);
  // fixing screws along the crests, in rows
  const screws = new Float32Array(n);
  const rows = 4;
  for (let r = 0; r < rows; r++) {
    const y = (r + 0.5) * size / rows + (rnd() - 0.5) * 5;
    for (let c = 0; c < RIDGES; c++) {
      const x = (c + 0.09) * size / RIDGES;
      stampDome(h, size, x, y, 3.2, 0.16, 0.4);
      stampBlob(screws, size, x, y, 4.5, 1, 1, 0.3);
      stampStreak(screws, size, x, y + 3, 26 + rnd() * 80, 2.4 + rnd() * 2, 0.85);
    }
  }
  const height = normalize01(h);

  const P = rgbPlanes(n, C.zinc);
  blendMask(P, C.steelDark, spangle, 0.5, -0.35);
  blendMask(P, C.steel, remap(spangle, 0.5, 0.9), 0.55);
  blendMask(P, C.rust, rustMask, 0.55);
  blendMask(P, C.rustDark, remap(rustMask, 0.72, 1.0), 0.40);
  blendMask(P, C.rustLight, screws, 0.55);
  blendMask(P, C.grime, remap(macro, 0.68, 1.0), 0.3);
  shadeByField(P, height, 0.86, 1.1);
  jitterHue(P, rnd, 0.04);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    const r = clamp01(rustMask[i] + screws[i] * 0.5);
    rough[i] = lerp(0.38 + micro[i] * 0.14 + spangle[i] * 0.1, 0.92, r);
    metal[i] = 1 - r * 0.92;
  }
  return { albedo: P, height, rough, metal, heightMetres: 0.026, tileMetres: 2.0, size };
}

// --- shipping-container panel ---------------------------------------------
function genContainer(size) {
  const n = size * size, rnd = mulberry32(5150);
  const RIDGES = 9;
  const macro = fbm(size, 5, 6, 401);
  const micro = fbm(size, 200, 2, 411);
  const chalk = fbm(size, 14, 5, 421);
  // Kept fine-grained: the per-instance livery colour multiplies this albedo,
  // so broad dark patches crush to black under a saturated tint.
  const rustMask = remap(warp(fbm(size, 12, 6, 431), size, fbm(size, 8, 4, 432), fbm(size, 8, 4, 433), size * 0.02), 0.55, 0.82);

  const h = new Float32Array(n);
  for (let y = 0, i = 0; y < size; y++) {
    for (let x = 0; x < size; x++, i++) {
      const u = (x / size) * RIDGES, f = u - Math.floor(u);
      let p;
      if (f < 0.3) p = 0; else if (f < 0.42) p = (f - 0.3) / 0.12;
      else if (f < 0.72) p = 1; else if (f < 0.84) p = 1 - (f - 0.72) / 0.12; else p = 0;
      // top and bottom rails are flat plate, not corrugated
      const v = y / size;
      const rail = smoothstep(0.085, 0.11, v) * (1 - smoothstep(0.89, 0.915, v));
      h[i] = p * 0.7 * rail + 0.15 + micro[i] * 0.04 + macro[i] * 0.05;
      if (rail < 0.5) h[i] += 0.1;
    }
  }
  for (let i = 0; i < 34; i++) stampDome(h, size, rnd() * size, rnd() * size, 6 + rnd() * 34, -0.2 - rnd() * 0.22, 1.2);
  // weld beads along the rail seams
  for (const v of [0.1, 0.9]) {
    const y = v * size;
    for (let x = 0; x < size; x += 3) stampDome(h, size, x, y + Math.sin(x * 0.4) * 1.2, 2.6, 0.12, 0.4);
  }
  const height = normalize01(h);

  // painted white-ish base; per-instance colour comes from material.color so one
  // texture serves the whole container yard in different liveries
  const P = rgbPlanes(n, [0.86, 0.86, 0.85]);
  shadeByField(P, chalk, 0.8, 1.05);
  blendMask(P, [0.55, 0.54, 0.52], remap(macro, 0.55, 0.95), 0.4);
  blendMask(P, C.rust, rustMask, 0.50);
  blendMask(P, C.rustDark, remap(rustMask, 0.78, 1.0), 0.32);
  const runs = new Float32Array(n);
  for (let i = 0; i < 60; i++) stampStreak(runs, size, rnd() * size, rnd() * size * 0.7, 50 + rnd() * 300, 2 + rnd() * 8, 0.85);
  blendMask(P, C.rustLight, runs, 0.4);
  shadeByField(P, height, 0.84, 1.12);
  jitterHue(P, rnd, 0.045);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    const r = clamp01(rustMask[i] * 1.1 + runs[i] * 0.3);
    rough[i] = lerp(0.5 + chalk[i] * 0.2 + micro[i] * 0.08, 0.93, r);
    metal[i] = r > 0.75 ? 0.1 : 0.0;
  }
  return { albedo: P, height, rough, metal, heightMetres: 0.05, tileMetres: 2.4, size };
}

// --- rusted painted steel (barriers, doors, tanks, tower frames) -----------
function genPaintedSteel(size) {
  const n = size * size, rnd = mulberry32(6060);
  const macro = fbm(size, 6, 6, 501);
  const micro = fbm(size, 220, 2, 511);
  const chip = remap(warp(fbm(size, 8, 6, 521), size, fbm(size, 14, 4, 522), fbm(size, 14, 4, 523), size * 0.03), 0.53, 0.63);
  const rustEdge = ridged(fbm(size, 10, 5, 531), 3);

  const h = new Float32Array(n);
  for (let i = 0; i < n; i++) h[i] = 0.5 + macro[i] * 0.1 + micro[i] * 0.08 - chip[i] * 0.22;
  // pressed panel seams
  for (let k = 1; k < 3; k++) {
    const y = k * size / 3;
    stampSegment(h, size, -2, y, size + 2, y, 4, -0.22);
    stampSegment(h, size, -2, y - 3, size + 2, y - 3, 2, 0.08);
  }
  // bolt heads on a grid, each with a rust run beneath it
  const bolts = new Float32Array(n), runs = new Float32Array(n);
  for (let by = 0; by < 4; by++) for (let bx = 0; bx < 4; bx++) {
    const x = (bx + 0.5) * size / 4 + (rnd() - 0.5) * 8, y = (by + 0.5) * size / 4 + (rnd() - 0.5) * 8;
    stampDome(h, size, x, y, 6.5, 0.3, 0.35);
    stampDome(h, size, x, y, 2.4, -0.14, 0.5);
    stampBlob(bolts, size, x, y, 8, 1, 1, 0.35);
    stampStreak(runs, size, x, y + 6, 40 + rnd() * 150, 3 + rnd() * 4, 0.9);
  }
  // scratches
  for (let i = 0; i < 90; i++) {
    const a = rnd() * Math.PI * 2, x = rnd() * size, y = rnd() * size, L = 12 + rnd() * 120;
    stampSegment(h, size, x, y, x + Math.cos(a) * L, y + Math.sin(a) * L, 1.2 + rnd() * 1.6, -0.12);
  }
  const height = normalize01(h);

  const P = rgbPlanes(n, [1, 1, 1]);      // white base: material.color supplies the livery
  shadeByField(P, macro, 0.78, 1.02);
  blendMask(P, [0.6, 0.59, 0.57], remap(micro, 0.5, 1.0), 0.22);
  const rustField = new Float32Array(n);
  for (let i = 0; i < n; i++) rustField[i] = clamp01(chip[i] * 1.2 + rustEdge[i] * chip[i] * 0.8 + runs[i] * 0.55 + bolts[i] * 0.2);
  blendMask(P, C.rustLight, rustField, 0.95);
  blendMask(P, C.rustDark, remap(rustField, 0.6, 1.0), 0.7);
  blendMask(P, C.grime, remap(macro, 0.72, 1.0), 0.32);
  shadeByField(P, height, 0.88, 1.08);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    const r = rustField[i];
    rough[i] = lerp(0.44 + macro[i] * 0.18 + micro[i] * 0.1, 0.9, clamp01(r * 1.3));
    metal[i] = r > 0.85 ? 0.12 : (chip[i] > 0.9 ? 1 : 0);
  }
  return { albedo: P, height, rough, metal, heightMetres: 0.008, tileMetres: 1.7, size, paintable: true };
}

// --- heavy raw rust (barrels, scrap, old machinery) -----------------------
function genRustedSteel(size) {
  const n = size * size, rnd = mulberry32(7070);
  const macro = fbm(size, 5, 6, 601);
  const meso = fbm(size, 26, 5, 611);
  const micro = fbm(size, 190, 2, 621);
  const flake = remap(ridged(fbm(size, 16, 5, 631), 2), 0.3, 0.75);

  const h = new Float32Array(n);
  for (let i = 0; i < n; i++) h[i] = macro[i] * 0.4 + meso[i] * 0.35 + micro[i] * 0.12 + flake[i] * 0.2;
  for (let i = 0; i < 260; i++) stampDome(h, size, rnd() * size, rnd() * size, 3 + rnd() * 16, (rnd() < 0.5 ? -1 : 1) * (0.1 + rnd() * 0.25), 0.9);
  const height = normalize01(h);

  const P = rgbPlanes(n, C.rust);
  blendMask(P, C.rustDark, macro, 1.1, -0.4);
  blendMask(P, C.rustLight, meso, 0.85, -0.2);
  blendMask(P, [0.32, 0.26, 0.22], remap(flake, 0.55, 1.0), 0.6);
  blendMask(P, C.steelDark, remap(macro, 0.86, 1.0), 0.5);   // occasional bare metal
  shadeByField(P, height, 0.78, 1.16);
  jitterHue(P, rnd, 0.07);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    rough[i] = clamp01(0.82 + micro[i] * 0.16 - macro[i] * 0.1);
    metal[i] = macro[i] > 0.88 ? 0.9 : 0.08;
  }
  return { albedo: P, height, rough, metal, heightMetres: 0.014, tileMetres: 1.3, size };
}

// --- sandbag hessian -------------------------------------------------------
function genSandbag(size) {
  const n = size * size, rnd = mulberry32(8080);
  const THREADS = 34;
  const macro = fbm(size, 5, 5, 701);
  const fibre = fbm(size, 200, 2, 711);
  const stain = remap(fbm(size, 7, 5, 721), 0.45, 0.75);

  const h = new Float32Array(n);
  for (let y = 0, i = 0; y < size; y++) {
    for (let x = 0; x < size; x++, i++) {
      const u = (x / size) * THREADS, v = (y / size) * THREADS;
      const cu = Math.floor(u), cv = Math.floor(v);
      const fu = u - cu, fv = v - cv;
      // plain weave: alternate which thread is on top per cell
      const over = ((cu + cv) & 1) === 0;
      const warpT = Math.sin(fu * Math.PI);
      const weftT = Math.sin(fv * Math.PI);
      h[i] = (over ? warpT * 0.75 + weftT * 0.3 : weftT * 0.75 + warpT * 0.3) * 0.55
        + macro[i] * 0.3 + fibre[i] * 0.12;
    }
  }
  for (let i = 0; i < 60; i++) {   // loose fibres
    const a = rnd() * Math.PI * 2, x = rnd() * size, y = rnd() * size, L = 6 + rnd() * 26;
    stampSegment(h, size, x, y, x + Math.cos(a) * L, y + Math.sin(a) * L, 1.4, 0.16);
  }
  const height = normalize01(h);

  const P = rgbPlanes(n, C.sandbag);
  blendMask(P, C.sandDark, macro, 1.0, -0.35);
  blendMask(P, C.grime, stain, 0.4);
  blendMask(P, C.sandPale, remap(fibre, 0.55, 0.95), 0.3);
  shadeByField(P, height, 0.72, 1.2);
  jitterHue(P, rnd, 0.07);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) rough[i] = clamp01(0.88 + fibre[i] * 0.1 - macro[i] * 0.06);
  return { albedo: P, height, rough, metal, heightMetres: 0.006, tileMetres: 0.55, size };
}

// --- wooden crate ----------------------------------------------------------
function genWood(size) {
  const n = size * size, rnd = mulberry32(9090);
  const PLANKS = 6;
  const macro = fbm(size, 6, 5, 801);
  const micro = fbm(size, 180, 2, 811);
  // grain: an fBm squashed 10:1 so the noise elongates along the plank
  const grainSrc = fbm(size, 10, 6, 821);
  const grain = new Float32Array(n);
  for (let y = 0, i = 0; y < size; y++) {
    for (let x = 0; x < size; x++, i++) {
      const gx = (x / size) * 1.0, gy = (y / size) * 0.1 + macro[i] * 0.05;
      let v = 0, a = 1, s = 0;
      for (let o = 0; o < 3; o++) {
        v += a * grainSrc[(((gy * (1 << o) * size) | 0) % size) * size + (((gx * (1 << o) * size) | 0) % size)];
        s += a; a *= 0.5;
      }
      grain[i] = v / s;
    }
  }

  const h = new Float32Array(n);
  const plankId = new Float32Array(n);
  for (let y = 0, i = 0; y < size; y++) {
    const v = (y / size) * PLANKS, pi = Math.floor(v), fv = v - pi;
    const idv = hash01(pi);
    for (let x = 0; x < size; x++, i++) {
      plankId[i] = idv;
      const gap = smoothstep(0.0, 0.035, fv) * (1 - smoothstep(0.965, 1.0, fv));
      h[i] = gap * 0.55 + 0.1 + Math.sin(grain[i] * 22) * 0.05 + micro[i] * 0.07 + idv * 0.06;
    }
  }
  // knots
  for (let i = 0; i < 9; i++) {
    const x = rnd() * size, y = rnd() * size, r = 6 + rnd() * 14;
    stampDome(h, size, x, y, r, -0.18, 1.3);
    stampDome(h, size, x, y, r * 0.45, 0.16, 0.6);
  }
  // nails
  for (let p = 0; p < PLANKS; p++) for (let k = 0; k < 4; k++) {
    const x = (k + 0.5) * size / 4 + (rnd() - 0.5) * 12, y = (p + 0.5) * size / PLANKS + (rnd() - 0.5) * 10;
    stampDome(h, size, x, y, 3, 0.22, 0.4);
  }
  // splinters / chipped edges
  for (let i = 0; i < 70; i++) {
    const a = rnd() * 0.5 - 0.25, x = rnd() * size, y = rnd() * size, L = 8 + rnd() * 50;
    stampSegment(h, size, x, y, x + Math.cos(a) * L, y + Math.sin(a) * L, 1.4 + rnd() * 2, -0.16);
  }
  const height = normalize01(h);

  const P = rgbPlanes(n, C.wood);
  for (let i = 0; i < n; i++) { const k = 0.8 + plankId[i] * 0.4; P[0][i] *= k; P[1][i] *= k; P[2][i] *= k; }
  blendMask(P, C.woodDark, mapf(grain, (v) => clamp01(Math.abs(Math.sin(v * 22)) * 0.9)), 0.65);
  blendMask(P, C.grime, remap(macro, 0.6, 1.0), 0.4);
  blendMask(P, C.sandPale, remap(micro, 0.6, 1.0), 0.16);   // sun-bleaching
  shadeByField(P, height, 0.7, 1.14);
  jitterHue(P, rnd, 0.05);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) rough[i] = clamp01(0.76 + micro[i] * 0.16 + macro[i] * 0.08);
  return { albedo: P, height, rough, metal, heightMetres: 0.007, tileMetres: 1.1, size };
}
function hash01(i) { const x = Math.sin(i * 127.1) * 43758.5453; return x - Math.floor(x); }
function mapf(src, fn) { const o = new Float32Array(src.length); for (let i = 0; i < src.length; i++) o[i] = fn(src[i]); return o; }

// --- plaster over brick ----------------------------------------------------
function genPlasterBrick(size) {
  const n = size * size, rnd = mulberry32(1212);
  const COLS = 10, ROWS = 32;                    // 0.24 x 0.075 m at a 2.4 m tile
  const macro = fbm(size, 5, 6, 901);
  const micro = fbm(size, 190, 3, 911);
  const plasterMask = remap(warp(fbm(size, 11, 6, 921), size, fbm(size, 10, 4, 922), fbm(size, 10, 4, 923), size * 0.02), 0.20, 0.58);

  const brickH = new Float32Array(n), brickTone = new Float32Array(n), mortarM = new Float32Array(n);
  for (let y = 0, i = 0; y < size; y++) {
    const rv = (y / size) * ROWS, row = Math.floor(rv), fr = rv - row;
    const off = (row & 1) ? 0.5 : 0;
    for (let x = 0; x < size; x++, i++) {
      const cv = (x / size) * COLS + off, col = Math.floor(cv), fc = cv - col;
      const jx = smoothstep(0.0, 0.05, fc) * (1 - smoothstep(0.95, 1.0, fc));
      const jy = smoothstep(0.0, 0.14, fr) * (1 - smoothstep(0.86, 1.0, fr));
      const brick = Math.min(jx, jy);
      mortarM[i] = 1 - brick;
      const id = hash01(row * 37 + col * 91);
      brickTone[i] = id;
      brickH[i] = brick * (0.5 + id * 0.16) + micro[i] * 0.06;
    }
  }

  const h = new Float32Array(n);
  for (let i = 0; i < n; i++) h[i] = lerp(brickH[i], 0.85 + macro[i] * 0.12 + micro[i] * 0.05, plasterMask[i]);
  // ragged plaster edges — chip the boundary so it is not a clean noise contour
  for (let i = 0; i < 220; i++) {
    const x = rnd() * size, y = rnd() * size;
    if (plasterMask[(y | 0) * size + (x | 0)] < 0.35 || plasterMask[(y | 0) * size + (x | 0)] > 0.85) continue;
    stampDome(h, size, x, y, 3 + rnd() * 11, -0.3, 1.4);
  }
  // cracks in the plaster only
  for (let i = 0; i < 12; i++) stampCrack(h, size, rnd, { length: size * (0.15 + rnd() * 0.4), width: 1.4 + rnd() * 2, amp: -0.35, wander: 0.3, branch: 0.6 });
  const height = normalize01(h);

  const P = rgbPlanes(n, C.brick);
  for (let i = 0; i < n; i++) { const k = 0.72 + brickTone[i] * 0.55; P[0][i] *= k; P[1][i] *= k * 0.98; P[2][i] *= k * 0.95; }
  blendMask(P, C.brickDark, remap(micro, 0.45, 0.95), 0.35);
  blendMask(P, C.mortar, mortarM, 0.92);
  blendMask(P, C.plaster, plasterMask, 0.94);
  blendMask(P, C.concretePale, mapf(plasterMask, (v) => (v > 0.7 ? 1 : 0)), 0.25);
  const streaks = new Float32Array(n);
  for (let i = 0; i < 30; i++) stampStreak(streaks, size, rnd() * size, rnd() * size, 70 + rnd() * 300, 4 + rnd() * 14, 0.8);
  blendMask(P, C.grime, streaks, 0.34);
  blendMask(P, C.moss, remap(macro, 0.78, 1.0), 0.22);
  shadeByField(P, height, 0.8, 1.12);
  jitterHue(P, rnd, 0.05);

  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) rough[i] = clamp01(lerp(0.86 + micro[i] * 0.1, 0.72 + macro[i] * 0.16, plasterMask[i]) - streaks[i] * 0.1);
  return { albedo: P, height, rough, metal, heightMetres: 0.02, tileMetres: 2.4, size };
}

// --- steel walkway grating (alpha) ----------------------------------------
function genGrating(size) {
  const n = size * size, rnd = mulberry32(1414);
  const BARS = 8, RODS = 4;
  const micro = fbm(size, 160, 2, 1001);
  const rust = remap(fbm(size, 6, 5, 1011), 0.5, 0.8);

  const h = new Float32Array(n), alpha = new Float32Array(n);
  for (let y = 0, i = 0; y < size; y++) {
    const rv = (y / size) * RODS, fr = Math.abs((rv - Math.floor(rv)) - 0.5) * 2;
    for (let x = 0; x < size; x++, i++) {
      const bv = (x / size) * BARS, fb = Math.abs((bv - Math.floor(bv)) - 0.5) * 2;
      const bar = fb > 0.78 ? 1 : 0;         // bearing bars (thin, vertical)
      const rod = fr > 0.88 ? 1 : 0;         // cross rods
      const solid = Math.max(bar, rod);
      alpha[i] = solid;
      h[i] = bar * 0.9 + rod * 0.55 + micro[i] * 0.08;
    }
  }
  const height = normalize01(h);
  const P = rgbPlanes(n, C.steelDark);
  blendMask(P, C.steel, remap(micro, 0.4, 0.9), 0.5);
  blendMask(P, C.rust, rust, 0.6);
  shadeByField(P, height, 0.7, 1.15);
  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) { rough[i] = clamp01(0.5 + rust[i] * 0.4 + micro[i] * 0.12); metal[i] = rust[i] > 0.7 ? 0.15 : 1; }
  return { albedo: P, height, rough, metal, alpha, heightMetres: 0.01, tileMetres: 0.5, size };
}

// --- chain-link fence mesh (alpha) ----------------------------------------
function genChainlink(size) {
  const n = size * size, rnd = mulberry32(1616);
  const DIAG = 11;                      // ~90 mm aperture at a 1 m tile
  const micro = fbm(size, 150, 2, 1101);
  const h = new Float32Array(n), alpha = new Float32Array(n);
  const wire = 0.085;                   // half-width in cell units
  for (let y = 0, i = 0; y < size; y++) {
    const v = y / size;
    for (let x = 0; x < size; x++, i++) {
      const u = x / size;
      const a = ((u + v) * DIAG) % 1, b = ((u - v) * DIAG + 10) % 1;
      const da = Math.abs(a - 0.5), db = Math.abs(b - 0.5);
      const inA = da > 0.5 - wire, inB = db > 0.5 - wire;
      alpha[i] = inA || inB ? 1 : 0;
      // the strand that is "on top" alternates, which is what makes woven mesh
      // read as woven rather than as a printed grid
      const top = ((Math.floor((u + v) * DIAG) + Math.floor((u - v) * DIAG)) & 1) === 0;
      const ha = inA ? (1 - da / (0.5)) : 0, hb = inB ? (1 - db / 0.5) : 0;
      h[i] = (top ? ha * 1.0 + hb * 0.4 : hb * 1.0 + ha * 0.4) + micro[i] * 0.05;
    }
  }
  const height = normalize01(h);
  const P = rgbPlanes(n, C.steel);
  blendMask(P, C.steelDark, remap(micro, 0.4, 0.9), 0.55);
  blendMask(P, C.rust, remap(fbm(size, 7, 5, 1111), 0.6, 0.9), 0.5);
  shadeByField(P, height, 0.62, 1.2);
  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) { rough[i] = clamp01(0.42 + micro[i] * 0.2); metal[i] = 1; }
  return { albedo: P, height, rough, metal, alpha, heightMetres: 0.004, tileMetres: 1.0, size };
}

// --- polyethylene tarp -----------------------------------------------------
function genTarp(size) {
  const n = size * size, rnd = mulberry32(1818);
  const W = 60;
  const macro = fbm(size, 6, 5, 1201);
  const micro = fbm(size, 170, 2, 1211);
  const h = new Float32Array(n);
  for (let y = 0, i = 0; y < size; y++) {
    for (let x = 0; x < size; x++, i++) {
      const u = (x / size) * W, v = (y / size) * W;
      const over = ((Math.floor(u) + Math.floor(v)) & 1) === 0;
      const a = Math.sin((u - Math.floor(u)) * Math.PI), b = Math.sin((v - Math.floor(v)) * Math.PI);
      h[i] = (over ? a * 0.7 + b * 0.3 : b * 0.7 + a * 0.3) * 0.4 + macro[i] * 0.5 + micro[i] * 0.1;
    }
  }
  for (let i = 0; i < 40; i++) {   // creases
    const a = rnd() * Math.PI * 2, x = rnd() * size, y = rnd() * size, L = 40 + rnd() * 200;
    stampSegment(h, size, x, y, x + Math.cos(a) * L, y + Math.sin(a) * L, 3 + rnd() * 5, -0.2);
  }
  const height = normalize01(h);
  const P = rgbPlanes(n, [1, 1, 1]);
  shadeByField(P, macro, 0.7, 1.05);
  blendMask(P, C.grime, remap(macro, 0.62, 1.0), 0.4);
  blendMask(P, [0.5, 0.5, 0.48], remap(micro, 0.5, 1.0), 0.2);
  shadeByField(P, height, 0.84, 1.1);
  const rough = new Float32Array(n), metal = new Float32Array(n);
  for (let i = 0; i < n; i++) rough[i] = clamp01(0.62 + micro[i] * 0.2 + macro[i] * 0.12);
  return { albedo: P, height, rough, metal, heightMetres: 0.004, tileMetres: 1.6, size, paintable: true };
}

// ===========================================================================
const GENERATORS = {
  concrete: { fn: genConcrete, size: 1024 },
  sand: { fn: genSand, size: 1024 },
  asphalt: { fn: genAsphalt, size: 1024 },
  corrugated: { fn: genCorrugated, size: 1024 },
  container: { fn: genContainer, size: 1024 },
  paintedSteel: { fn: genPaintedSteel, size: 1024 },
  plasterBrick: { fn: genPlasterBrick, size: 1024 },
  rustedSteel: { fn: genRustedSteel, size: 512 },
  sandbag: { fn: genSandbag, size: 512 },
  wood: { fn: genWood, size: 512 },
  grating: { fn: genGrating, size: 512 },
  chainlink: { fn: genChainlink, size: 512 },
  tarp: { fn: genTarp, size: 512 },
};

export class TextureLibrary {
  constructor(renderer, opts = {}) {
    this.cache = new Map();
    this.scale = opts.scale ?? 1;
    const maxA = renderer?.capabilities?.getMaxAnisotropy?.() ?? 1;
    this.aniso = Math.min(4, maxA);
    this.stats = { ms: 0, bytes: 0 };
  }

  get(name) {
    if (this.cache.has(name)) return this.cache.get(name);
    const g = GENERATORS[name];
    if (!g) throw new Error(`texgen: unknown texture set "${name}"`);
    const t0 = performance.now();
    const size = Math.max(128, Math.round((g.size * this.scale) / 128) * 128);
    const d = g.fn(size);

    const ao = aoFromHeight(d.height, d.size, 10, 1.15);
    const albedoBytes = toBytes(d.albedo, d.size);
    if (d.alpha) {                    // punch alpha into the albedo texture
      for (let i = 0; i < d.alpha.length; i++) albedoBytes[i * 4 + 3] = clamp01(d.alpha[i]) * 255;
    }
    const set = {
      map: makeTex(albedoBytes, d.size, true, this.aniso),
      normalMap: makeTex(normalFromHeight(d.height, d.size, d.heightMetres, d.tileMetres), d.size, false, this.aniso),
      ormMap: makeTex(packORM(ao, d.rough, d.metal, d.size), d.size, false, this.aniso),
      tileMetres: d.tileMetres,
      heightMetres: d.heightMetres,
      hasAlpha: !!d.alpha,
      size: d.size,
    };
    set.map.name = `${name}_albedo`;
    set.normalMap.name = `${name}_normal`;
    set.ormMap.name = `${name}_orm`;
    this.stats.ms += performance.now() - t0;
    this.stats.bytes += d.size * d.size * 4 * 3;
    this.cache.set(name, set);
    return set;
  }

  /** Warm the whole library up front so nothing hitches mid-frame. */
  preload(names) { for (const n of names) this.get(n); return this; }
}

export const TEXTURE_NAMES = Object.keys(GENERATORS);
